# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: PublicNuget
- name: buildConfiguration
  value: 'Release'
- name: majorVersion
  value: 1
- name: minorVersion
  value: 0
- name: patchVersion
  value: $(Build.BuildId)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet pack  -p:PackageVersion=$(majorVersion).$(minorVersion).$(patchVersion) --configuration $(buildConfiguration) --include-symbols
  displayName: 'dotnet pack $(buildConfiguration)'
- script: dotnet nuget push Markdig.Slack.$(majorVersion).$(minorVersion).$(patchVersion).nupkg -k $(apiKey) -s https://api.nuget.org/v3/index.json
  displayName: 'dotnet push'

